### PR TITLE
Printing collision in inverse purple text to terminal

### PR DESCRIPTION
**Pull request by bobhendrikx**
Okay like this? 
Screenshot from 2021-05-25 14-31-39

### CODE REVIEW

**Comment by PetervDooren** [comment]
I would up the contrast on that, This is hard to see. Other than that this is fine

**Comment by bobhendrikx** [comment]
true, ill make it green and merge it into master!

**Comment by PetervDooren** [comment]
Okay, but maybe yellow is a better warning colour than green

**Comment by bobhendrikx** [comment]
oke yellow :)

**Pull request merged**
