### PR TITLE
Mrc2020

### PR DESCRIPTION
**Pull request by bobhendrikx**
Hey peoples,

Could you try this on your PC, see if you think it is correct. 
I would like you test: if it works, if the odometry works as expected, the tutorials still work. 
You should now see collision detection, omoetry drift that is different each time you restart the simulator and some objects that move out of the way. 

Further i would like your input on:
* How to configure the moving objects? I was thinking supplying a JSON file with an object list somewhere with init position, final position, length, width, pico_trigger_radius, and velocity...

To use the code:
* install the emc stuff
* Go to your ~/.emc folder, this is where all the emc stuff is kept. 
* in the src folder, in the emc-sim package, checkout this branch
* run emc-update
* run the simulator, ~~(run like `emc-sim --noslip` to disable drift)~~

PS ofcourse feel free to add commits on top of mine.

### CODE REVIEW

**Comment by bobhendrikx** [comment]
> @bobhendrikx Ik denk dat je geen CompositeShape nodig hebt, als het goed is, kan het ook met een gewone Shape.

Thanks, zal er naar kijken. Ik zag trouwens ook dat deze in jullie task board terecht komt, en ik zie niet of ik dat kan uit kan zetten.

**Comment by whoutman** [comment]
Some great progress Bob!

- How to configure the moving objects?
-- As discussed this morning, something like JSON or YAML should be sufficient, as long as there is a tutorial on the MRC-wiki for the students which explains how to configure it. Adding the config file as an argument when launching the simulator should be fine, right?
-- In this config file, I would propose to adapt the amount of slip for the odometry instead of providing a "no slip" argument. This makes it possible to make robust tests.
-- Printing the configuration parameters as a feedback would be of great help for the students
-- If the file is not provided, or if the file can not be read, a default set of parameters is chosen. The students get feedback in this case with some print statements.

- Is it possible to add some variance to the odometry? If I move forwards and backwards with the robot, it ends up in exactly the same place. 

- The moving objects make a single movement. Could they repetatively move backwards and forwards? Now it is "just" a single movement, while constant moving disturbances are applied if the movement is repetitive. Alternatively, a config-parameter could be added to make it repetitive or not. What do you thing?

**Comment by bobhendrikx** [comment]
>   -- As discussed this morning, something like JSON or YAML should be sufficient, as long as there is a tutorial on the MRC-wiki for the students which explains how to configure it. Adding the config file as an argument when launching the simulator should be fine, right?
>   -- In this config file, I would propose to adapt the amount of slip for the odometry instead of providing a "no slip" argument. This makes it possible to make robust tests.
>   -- Printing the configuration parameters as a feedback would be of great help for the students
>   -- If the file is not provided, or if the file can not be read, a default set of parameters is chosen. The students get feedback in this case with some print statements.
Agreed! will do these things

> * Is it possible to add some variance to the odometry? If I move forwards and backwards with the robot, it ends up in exactly the same place.
What did you have in mind here? RIght now the "variance" is indeed sampled only at startup. 

> * The moving objects make a single movement. Could they repetatively move backwards and forwards? Now it is "just" a single movement, while constant moving disturbances are applied if the movement is repetitive. Alternatively, a config-parameter could be added to make it repetitive or not. What do you thing?
This could be done, but i prefer to finish a version that doesnt do this first. If we have time we will add this.

**Comment by bobhendrikx** [comment]
About the odometry, i think we need to keep it simple, and have only a a true or false for uncertain odom. In the latter case it is perfect. In the former we add a litte bit of wheel uncertainty that we change every few seconds or so (random sampled). This amount of wheel uncertainty is then also representative for the challenges. I think we overcomplicate things if we give m al sorts of settings to play with.

**Comment by whoutman** [comment]
Ok, lets go for it! Would be nice if we can finish and test it 🙂
________________________________

**Comment by bobhendrikx** [comment]
Usage:

```emc-sim --config /home/bob/.emc/system/src/emc_simulator/data/config.json --map /home/bob/.emc/system/src/emc_simulator/data/heightmap.pgm
```
(replace with your home folder)

**Comment by Hauwww** [comment]
Ubuntu 18.04, ros-melodic

Following errors when performing catkin-make:

In file included from /home/hao/.emc/system/src/emc_simulator/src/main.cpp:11:0:
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:85:12: error: ‘optional’ in namespace ‘boost’ does not name a template type
     boost::optional<bool> show_full_map;
            ^~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:86:12: error: ‘optional’ in namespace ‘boost’ does not name a template type
     boost::optional<bool> uncertain_odom;
            ^~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:87:12: error: ‘optional’ in namespace ‘boost’ does not name a template type
     boost::optional<std::vector<MovingObject>> moving_objects;
            ^~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h: In constructor ‘Config::Config(std::__cxx11::string)’:
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:36:9: error: ‘uncertain_odom’ was not declared in this scope
         uncertain_odom = b;
         ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:41:9: error: ‘show_full_map’ was not declared in this scope
         show_full_map = b2;
         ^~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:72:9: error: ‘moving_objects’ was not declared in this scope
         moving_objects = ms;
         ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:72:9: note: suggested alternative: ‘MovingObject’
         moving_objects = ms;
         ^~~~~~~~~~~~~~
         MovingObject
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h: In member function ‘void Config::print()’:
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:77:44: error: ‘uncertain_odom’ was not declared in this scope
         std::cout << "Uncertain odom: " << uncertain_odom.value() << std::endl;
                                            ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:78:43: error: ‘show_full_map’ was not declared in this scope
         std::cout << "Show full map: " << show_full_map.value() << std::endl;
                                           ^~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:79:37: error: ‘moving_objects’ was not declared in this scope
         std::cout << "imported " << moving_objects.value().size() << " moving objects" << std::endl;
                                     ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/jsonconfig.h:79:37: note: suggested alternative: ‘MovingObject’
         std::cout << "imported " << moving_objects.value().size() << " moving objects" << std::endl;
                                     ^~~~~~~~~~~~~~
                                     MovingObject
/home/hao/.emc/system/src/emc_simulator/src/main.cpp: In function ‘int main(int, char**)’:
/home/hao/.emc/system/src/emc_simulator/src/main.cpp:120:57: error: ‘class Config’ has no member named ‘moving_objects’
     for(std::vector<MovingObject>::iterator it = config.moving_objects.value().begin(); it != config.moving_objects.value().end(); ++it) {
                                                         ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/main.cpp:120:102: error: ‘class Config’ has no member named ‘moving_objects’
 ::iterator it = config.moving_objects.value().begin(); it != config.moving_objects.value().end(); ++it) {
                                                                     ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/main.cpp:164:16: error: ‘class Config’ has no member named ‘uncertain_odom’
     if(!config.uncertain_odom.value()){
                ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/main.cpp:211:61: error: ‘class Config’ has no member named ‘moving_objects’
         for(std::vector<MovingObject>::iterator it = config.moving_objects.value().begin(); it != config.moving_objects.value().end(); ++it){
                                                             ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/main.cpp:211:106: error: ‘class Config’ has no member named ‘moving_objects’
 ::iterator it = config.moving_objects.value().begin(); it != config.moving_objects.value().end(); ++it){
                                                                     ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/main.cpp:253:61: error: ‘class Config’ has no member named ‘moving_objects’
         for(std::vector<MovingObject>::iterator it = config.moving_objects.value().begin(); it != config.moving_objects.value().end(); ++it){
                                                             ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/main.cpp:253:106: error: ‘class Config’ has no member named ‘moving_objects’
 ::iterator it = config.moving_objects.value().begin(); it != config.moving_objects.value().end(); ++it){
                                                                     ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/main.cpp:297:19: error: ‘class Config’ has no member named ‘uncertain_odom’
         if(config.uncertain_odom.value() && time.sec%6 == 0 ){
                   ^~~~~~~~~~~~~~
/home/hao/.emc/system/src/emc_simulator/src/main.cpp:321:73: error: ‘class Config’ has no member named ‘show_full_map’
         visualization::visualize(world, robot_id, collision, config.show_full_map.value());
                                                                     ^~~~~~~~~~~~~
emc_simulator/CMakeFiles/pico_simulator.dir/build.make:62: recipe for target 'emc_simulator/CMakeFiles/pico_simulator.dir/src/main.cpp.o' failed
make[2]: *** [emc_simulator/CMakeFiles/pico_simulator.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:3965: recipe for target 'emc_simulator/CMakeFiles/pico_simulator.dir/all' failed
make[1]: *** [emc_simulator/CMakeFiles/pico_simulator.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by bobhendrikx** [comment]
Kijk dat zijn de betere boost errors, ik ga er naar kijken!

**Comment by bobhendrikx** [comment]
@Hauwww ik heb de boost include toegevoegd, kun je nog eens proberen?
Ik kan het lastig reproduceren op mijn systeem.

**Comment by Hauwww** [comment]
@bobhendrikx errors zijn weg

**Comment by Hauwww** [comment]
Screenshot from 2020-04-03 15-43-41

**Comment by Hauwww** [comment]
@bobhendrikx it works

**Comment by bobhendrikx** [comment]
also the odometry that you get back from the cplusplus interface? 
It does not do weird stuff? It should not but its good to make sure

**Comment by Hauwww** [comment]
@bobhendrikx kan een meer geavanceerd object_motion planner worden geimplementeerd? of door jou, of dat je me even toewijst waar ik in de software aanpassingen zou moeten maken?

Implementatie idee: 
De json file zou iets als dit moeten uitzien:
"objects":[
 {
    "length": 1.0,
    "width": 1.0,
    "trigger_radius": 1.0,
    "repeat": false,
    "velocity": 0.6,
    "total_poses": 4
    "pose_1": [x, y, z],
    "pose_2":[x, y, z],
    "pose_3":[x, y, z],
   "pose_4": [x,y,z]
}]

Waarbij een algoritme dan wordt gecreerd dat de poses gaat 'loopen' afhankelijk van de nummer die bij 'total_poses' staat. 
iets als [in python]:
for i in range(objects[0]["total_poses"]):
   pose = objects[0]["pose_" + str(i)]

**Comment by Hauwww** [comment]
> also the odometry that you get back from the cplusplus interface?
> It does not do weird stuff? It should not but its good to make sure

@bobhendrikx I do not get twist information, but do get pose information. At least, from rostopic echo /pico/odom. Here you can see example of two consequetive odom messages
Screenshot from 2020-04-03 15-56-58

**Comment by bobhendrikx** [comment]
the students dont have access to twist information i think.

**Comment by Hauwww** [comment]
@jsenden if you want to do the emc environment in ubuntu 18.04, then you need to make sure you change the output of variable EMC_ROS_DISTRO into melodic: EMC_ROS_DISTRO=melodic (line 9 in the setup.bash script; https://github.com/tue-robotics/emc-env/blob/master/setup.bash). You need to do this before the install.bash script - see https://github.com/tue-robotics/emc-env/blob/master/install.bash - goes past line 17. 

What I did, was that I first ran a modified install.bash script - such that the EMC package goes into the correct folder -  where I left everything out from line 17 onwards. afterwards, I modified the 'setup.bash' script where I changed the EMC_ROS_DISTRO variable. And then I ran the original install.bash script again.

**Comment by bobhendrikx** [comment]
@Hauwww zie hier:
https://github.com/tue-robotics/emc_simulator/blob/1b99ec4448c1890d236040442872030fd6fec26e/src/main.cpp#L211

Ik zou dan een JSON array gebruiken en geen JSON keys zoals in jouw voorbeeld. 
De vraag is in wat voor scenario een dergelijk staccato pad erg realistisch is..

**Comment by Hauwww** [comment]
@bobhendrikx de scenario die ik voor ogen had, is meer een persoon die toevallig van de ene kamer naar de andere kamer wilt lopen (en dan misschien terug). In dat geval lijkt me zo'n pad niet gelijk aan een rechtlijnig iets.

**Comment by Hauwww** [comment]
@bobhendrikx btw als een object bewogen heeft met 'repeat = false', kan dat object daarna weer bewegen? Een scenario die ik voor ogen heb is een deur die opeens sluit, terwijl de robot ernaartoe wilt bewegem, en dat de robot bijvoorbeeld ergens naartoe moet gaan (om een knop in te drukken) om de deur dan weer te openen. Of dat de deur alleen x seconde gesloten blijft.

**Comment by bobhendrikx** [comment]
> @bobhendrikx btw als een object bewogen heeft met 'repeat = false', kan dat object daarna weer bewegen?  

In de huidige implementatie kan dit niet

**Comment by bobhendrikx** [comment]
I have merged the changes into master, so that i can make the tutorials, if there are any comments let me know, @Hauwww if you want to implement your ideas, you can start a new branch.

**Pull request merged**
